spring:
  redis:
    host: localhost
    port: 6379
  aop:
    proxy-target-class: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: accounts
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
        service-id: configserver
      enabled: true 
  zipkin:
    discovery-client-enabled: true
    service:
      name: zipkin-server 
  boot:
    admin:
      client:
        username: "user"       #These two are needed so that the client
        password: "password"   #can register at the protected server api
        url:
        - ${ADMIN_SERVER_URL:http://localhost:9090/}
      
eureka:
  instance:
    instance-id: account-query
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

axon:
  eventhandling:
    processors:
      Accounts:
        source: kafkaMessageSource
        mode: TRACKING
  serializer:
    general: jackson
  distributed:
    enabled: true
    spring-cloud.fallback-to-http-get: true
    spring-cloud.fallback-url: /message-routing-information
  kafka:
    client-id: accountconsumer
    default-topic: account_topic
    consumer:
      group-id: account_group
      auto-offset-reset: earliest
      bootstrap-servers: 127.0.0.1:9092
    
security:
  oauth2:
    resource:
      jwt:
        key-uri: https://localhost:8769/uaa/oauth/token_key
      id: openid
      serviceId: ${PREFIX:}resource


# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: TRACE
    com.training.mjunction.usersvcs: ERROR
    org.springframework: ERROR
    org.hibernate: ERROR
    sun.rmi: ERROR
    org.reflections: ERROR
    sun.reflect: ERROR
    org.apache.coyote.http11: ERROR
    org.glassfish.jersey.internal.util: ERROR
    org.apache.tomcat.util.descriptor: ERROR
    org.apache.catalina.core: ERROR